# Generated by Django 4.1.3 on 2022-11-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_myuser_linkedin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='linkedin_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
