# Generated by Django 4.1.3 on 2022-11-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_brand_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(default='default.jpg', upload_to='brand'),
        ),
    ]
