# Generated by Django 4.1.3 on 2022-11-27 04:54

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_item',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_faculty',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_parent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_student',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
